- id: bats
  name: bats
  description: Run bats tests. https://github.com/bats-core/bats-core
  language: system
  entry: bats
  pass_filenames: false
- id: check-perl-syntax
  name: Check Perl Syntax
  description: Run perl -c on all perl scripts
  language: system
  # entry: perl -e 'use Cwd qw(cwd);print "(@ARGV)";$dir = cwd; print "cwd is $dir\n";'
  # entry: perl -ne 'my $status_code=system("perl -c $ARGV[0]"); print("status_code is $status_code for $ARGV[0]\n"); if ($status_code != 0) {exit -1;}'
  # entry: perl -E 'if($ENV{DEBUG}){print "\@ARGV contains (@ARGV)\n\n"}foreach(@ARGV){my $o=`perl -c $_ 2>&1`; if($ENV{DEBUG}){print("Script $_\nExit Code $?\nSTDOUT/STDERR $o\n")} if ($? != 0) {print $o;exit -1}}'
  entry: perl check-perl-syntax.pl
  pass_filenames: true
  # types: [perl]
  # files: \.pl$
  types: [file, perl]
  verbose: true
