name: Earthly
on:
  push:
jobs:
  tests:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: "latest"
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: run earthly for running tests
        run: earthly +run-all
